services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CostCalculationModule\Application\Calculator\Api\CalculatorInterface:
    class:  CostCalculationModule\Application\Calculator\Service\Calculator