services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CostCalculationModule\Infrastructure\Delivery\Api\DeliveryServiceInterface:
    class: CostCalculationModule\Infrastructure\Delivery\Service\AbstractDeliveryService