services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CostCalculationModule\Infrastructure\Order\Api\OrderInterface:
    class: CostCalculationModule\Infrastructure\Order\Service\Order