parameters:
  app.name: cost-calculation-module
  app.version: '1.0.0'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CostCalculationModule\Api\CalculatorDeliveryInterface:
    class:  CostCalculationModule\Service\CalculatorDelivery

  CostCalculationModule\Api\ConverterInterface:
    class: CostCalculationModule\Converter\AbstractConverter

  CostCalculationModule\Api\DeliveryServiceInterface:
    class: CostCalculationModule\Delivery\AbstractDeliveryService

  CostCalculationModule\Api\OrderInterface:
    class: CostCalculationModule\Service\Order

  CostCalculationModule\Api\ShippingInterface:
    class: CostCalculationModule\Service\Shipping
