services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CostCalculationModule\Infrastructure\Request\Api\RequestInterface:
    class: CostCalculationModule\Infrastructure\Request\Service\Request